packages:
  branch_codenames:
    master: focal-unstable
    production: focal-stable

jobs:
  wasd:
    builder: "golang"
    base: "quay.io/madebymany/build-bases:focal"
    environment:
      GO_PACKAGE_DIR: wasd
    packages:
      - type: debian
        name: wasd
        target: install
        repos:
          - mxm-public
        activates:
          - wasd-upgrade
