packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  wasd:
    builder: "golang"
    base: "quay.io/madebymany/build-bases:bionic"
    environment:
      GO_PACKAGE_DIR: wasd
      branches:
        master:
          TEST: test
    packages:
      - type: debian
        name: wasd
        target: install
        repos:
          - mxm-public
        activates:
          - wasd-upgrade
