packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  wasd:
    builder: "golang"
    base: "quay.io/madebymany/build-bases:trusty"
    environment:
      GO_PACKAGE_DIR: wasd
    packages:
      - type: debian
        name: wasd
        version: 0.0.3
        target: install
        repos:
          - mxm-public
        activates:
          - wasd-upgrade
